// Verbatim copy from SPEC.md Appendix A. Do not paraphrase — the copy has been proofread.
import { placeholders as p } from './placeholders';

export const copy = {
  announcement: {
    desktop: `Free nationwide shipping on orders ₱899+ · Cash on Delivery available · Ships from Metro Manila in ${p.deliveryDaysMetroManila} days`,
    mobile: 'Free shipping on ₱899+ · COD available · Ships from Metro Manila',
  },
  nav: [
    { label: 'How it works', href: '#how-it-works' },
    { label: 'See it in action', href: '#see-it-in-action' },
    { label: 'Bundles', href: '#bundles' },
    { label: 'Reviews', href: '#reviews' },
    { label: 'FAQ', href: '#faq' },
  ],
  hero: {
    tagline: { a: 'Something’s under the mat.', b: 'Your cat ', accent: 'has to know.' },
    leadDesktop: 'The Laro Hunt Mat hides a feather under a 60 cm mat and sweeps it around in random paths, like real prey. Press once, walk away, and let the hunt begin — quietly, session after session.',
    leadMobile: 'A feather hides under a 60 cm mat and sweeps around like real prey. Press once, walk away, let the hunt begin.',
    priceNoteDesktop: 'or ₱899 with a 3-feather refill — free shipping',
    priceNoteMobile: { pre: 'or ', price: '₱899', post: ' with 3 spare feathers & free shipping' },
    ratingDesktop: `[${p.rating.slice(1, -1)} · ${p.reviewCount.slice(1, -1)} reviews — connect live rating]`,
    ratingMobile: `[${p.rating.slice(1, -1)} · ${p.reviewCount.slice(1, -1)} reviews]`,
    buyNow: 'Buy now · COD available',
    watchDemoDesktop: 'Watch the 20-sec demo',
    watchDemoMobile: 'Watch the 20-second demo',
    trust: [
      { icon: 'cod', title: 'Cash on Delivery', sub: 'or GCash · Maya · cards' },
      { icon: 'truck', title: 'Free shipping ₱899+', sub: 'J&T · Flash · LBC nationwide' },
      { icon: 'feather', title: 'Spare feathers in the box', sub: 'refills from ₱149' },
      { icon: 'shield', title: '30-day Cat-Approved', sub: 'ignored it? full refund' },
    ],
    videoLabel: '20-sec demo',
    videoHook: { pre: 'Wait for it… ', accent: 'pounce.' },
    stickers: {
      speeds: '3 speeds',
      quietDesktop: 'Whisper-quiet motor',
      quietMobile: 'Whisper-quiet',
      typeC: 'Type-C rechargeable',
      feathers: 'Spare feathers included',
    },
  },
  marquee: ['Spare feathers included', '3 speed levels', 'Auto on/off', '60 cm hunting mat', 'USB Type-C', 'COD available', 'Whisper-quiet'],
  action: {
    eyebrow: 'See it in action',
    h2: 'Twenty seconds. One very serious cat.',
    pDesktop: 'Sound on — cats hear the feather rustle under the fabric before they see it. That wait-then-pounce beat is why these clips get shared.',
    pMobile: 'Sound on — cats hear the feather rustle before they see it.',
    playFull: 'Play full demo',
    clips: [
      { label: 'Press', caption: 'Press once.', image: 'videoPress', time: '0:07' },
      { label: 'Stalk', caption: 'She hears it. She waits.', image: 'videoStalk', time: '0:07' },
      { label: 'Pounce', caption: 'POUNCE.', image: 'videoPounce', time: '0:07' },
    ],
    ugcLabel: 'UGC slot · creator clip with permission',
    ugcMeta: '@creator · TikTok · [views]',
  },
  how: {
    eyebrow: 'How it works',
    h2: 'Press once. The mat does the rest.',
    p: 'No app, no batteries to buy, no supervising a wand for 20 minutes. It plays the way cats hunt.',
    steps: [
      { title: 'Press once', body: 'One button, three speeds. The LED colour shows the mode you picked.', image: 'videoPress' },
      { title: 'The feather hides and sweeps', body: 'A feather wand darts under the 60 cm mat in random paths, peeking out at the edges like real prey. The motor is whisper-quiet.', image: 'hub' },
      { title: 'Your cat stalks, waits, pounces', body: 'It runs a play session, then rests on its own. Recharge with the Type-C cable you already own.', image: 'videoPounce' },
    ],
    chips: [
      { icon: 'speed', label: '3 speeds' },
      { icon: 'random', label: 'Random 360° paths' },
      { icon: 'auto', label: 'Auto on/off' },
      { icon: 'usbc', label: 'USB Type-C' },
      { icon: 'quiet', label: 'Whisper-quiet' },
    ],
  },
  bundles: {
    eyebrow: 'Bundles',
    h2: 'Pick your bundle',
    p: 'Orders of ₱899 and up ship free anywhere in the Philippines. Max 2 mats per order — message us for multi-cat rescues.',
    singleMat: 'Single mat',
    freeShipping: 'FREE nationwide shipping',
    paidShipping: '+ ₱79 shipping',
    addon: { title: 'Add feather refill packs', sub: '3 natural feathers per pack · ₱149 · add up to 3 packs', plus: '+ ₱149' },
    cta: 'Continue to checkout',
    ctaNote: 'Guest checkout · Cash on Delivery, GCash, Maya, Visa, Mastercard',
  },
  shippingBand: {
    h2Desktop: 'Free nationwide shipping on orders ₱899+',
    h2Mobile: 'Free shipping on ₱899+',
    line: `Metro Manila ${p.deliveryDaysMetroManila} days · Provinces ${p.deliveryDaysProvinces} days · Tracking number sent by SMS`,
  },
  reviews: {
    eyebrow: 'Reviews',
    h2: 'Cat parents from QC to Davao',
    summary: `from ${p.reviewCount} verified PH orders — live from your reviews app`,
    sampleTag: 'Sample review',
    photoSlotDesktop: 'Customer photo slot',
    photoSlotMobile: 'Photo slot',
  },
  objections: {
    eyebrow: 'Worried your cat won’t care?',
    h2: 'We took the risk off you',
    cards: [
      { icon: 'shield', title: '30-day Cat-Approved Guarantee', body: 'If your cat ignores it after 30 days, send it back for a full refund. [Proposed policy]' },
      { icon: 'feather', title: 'Spare feathers in every box', body: 'Feathers wear out — that is the point. Spares are included and refills are ₱149.' },
      { icon: 'quiet', title: 'Whisper-quiet motor', body: 'No grinding noise. Skittish cats hear the feather, not the machine.' },
      { icon: 'bolt', title: '6-month motor warranty', body: 'Charging or motor issue? We replace the hub. [Proposed policy]' },
    ],
  },
  specs: {
    h2: 'Specs',
    rows: [
      ['Mat', '60 cm star-shaped taffeta cover, fish or duck print'],
      ['Hub', 'ABS plastic motor hub, one-button control, 3 speed levels with LED colours'],
      ['Feather wand', 'Approx. 23 cm natural feather, replaceable'],
      ['Power', `USB Type-C rechargeable · [${p.batteryMah.slice(1, -1)} battery, ${p.playtimePerCharge.slice(1, -1)} per charge — confirm]`],
      ['Play cycle', 'Automatic on/off: plays a session, then rests'],
      ['Best surface', 'Tile, wood or laminate floors; thin rugs'],
      ['For', 'Cats and kittens · supervised play'],
    ],
    boxH2: 'In the box',
    box: ['1 × Laro Hunt Mat cover (60 cm)', '1 × Motor hub', `${p.feathersInBox.replace(' [', ' × Feather wands [')}`, '1 × USB Type-C cable', 'Quick-start guide'],
    printNote: 'Choose fish or duck print at checkout',
  },
  faq: {
    eyebrow: 'FAQ',
    h2: 'Questions cat parents ask',
    side: 'Still unsure? Message us on Facebook or Viber — we reply within the day.',
    items: [
      { q: 'Will it work for a lazy or older cat?', a: 'Most cats react to the sound and the peeking feather within a day or two. Start on the slow speed, sprinkle a little catnip on the mat, and keep sessions short. If your cat still ignores it after 30 days, our Cat-Approved Guarantee covers a return.' },
      { q: 'Is it noisy?', a: 'The motor is whisper-quiet. Cats hear the soft rustle of the feather under the fabric, which is exactly what triggers the hunt.' },
      { q: 'How do I charge it and how long does it run?', a: 'Charge the hub with any USB Type-C cable. [Confirm with supplier: charge time and play time per charge.] It runs a play session, then rests on its own to save battery.' },
      { q: 'Is it safe for my cat?', a: 'The mat is taffeta fabric, the hub is ABS plastic, and the feathers are natural. Supervise play like any feather toy, and keep it away from small children.' },
      { q: 'Do you deliver outside Metro Manila?', a: `Yes. We ship nationwide via J&T, Flash Express or LBC — Metro Manila in ${p.deliveryDaysMetroManila} days, provinces in ${p.deliveryDaysProvinces} days. Cash on Delivery is available wherever our couriers offer it (almost everywhere); GCash, Maya and cards everywhere.` },
      { q: 'What if a feather wears out?', a: 'Spare feathers come in the box, and a 3-feather refill pack is ₱149. You can add up to three refill packs to any order.' },
    ],
  },
  finalCta: { h2: 'Ready for the pounce?', p: '₱799 · free shipping on bundles · Cash on Delivery available', button: 'Buy the Laro Hunt Mat' },
  footer: {
    tagline: 'Play, delivered. Automatic toys for Filipino cats and dogs, shipped from Metro Manila.',
    columns: [
      { title: 'Shop', links: [{ label: 'Laro Hunt Mat', href: '/' }, { label: 'Feather refills', href: '/#bundles' }, { label: 'Bundles', href: '/#bundles' }, { label: 'Coming soon: dog toys', href: '/' }] },
      { title: 'Help', links: [{ label: 'Shipping & delivery', href: '/policies/shipping' }, { label: 'Returns & 30-day guarantee', href: '/policies/returns' }, { label: 'Warranty', href: '/policies/returns' }, { label: 'Contact us', href: `mailto:${p.contactEmail}` }] },
      { title: 'Legal', links: [{ label: 'Privacy notice (RA 10173)', href: '/policies/privacy' }, { label: 'Terms of sale', href: '/policies/terms' }, { label: `DTI Reg. No. ${p.dtiRegNo}`, href: '/policies/terms' }, { label: `BIR TIN ${p.birTin}`, href: '/policies/terms' }] },
    ],
    weAccept: 'We accept',
    deliveredBy: 'Delivered by',
    seo: 'Laro Hunt Mat is an automatic hide-and-seek cat teaser toy — an interactive, rechargeable cat hunting mat with a moving feather for indoor cats in the Philippines. Also searched as: automatic cat toy Philippines, cat hunting mat, interactive cat toy, laruan ng pusa.',
    legal: `© 2026 Laro Pets · ${p.businessName} · ${p.businessAddress} · ${p.contactEmail}`,
  },
  stickyBar: { sub: 'COD · free ship on ₱899+', button: 'Buy now' },
  header: { buyNow: 'Buy now — ₱799' },
} as const;
